Fix #308: refer to MLContext validation steps from MLGraphBuilder
webmachinelearning/webnn pull request #332
Opened 2023-01-23 19:24 UTC by zolkis

Fix #308: refer to MLContext validation steps from MLGraphBuilder constructor

Minor change, adds reference to missing algorithm.

@anssiko PTAL

2023-01-23 19:26 UTC, zolkis commented
Looks like my editor stumbled upon line endings (trailing spaces) here as well.
Fortunately the diff is usable.

2023-01-24 09:11 UTC, anssiko requested changes
Thanks!

Protip: you can hide whitespace in GH diffs with `w=1` e.g. https://github.com/webmachinelearning/webnn/pull/332/files?diff=unified&w=1

2023-01-24 09:11 UTC, anssiko commented on index.bs
> +1.  If the <a>validate MLContext</a> steps given |context| return `false`, throw a "{{TypeError}}" and abort these steps.
Remove the _leading_ whitespace :-)

```suggestion
1. If the <a>validate MLContext</a> steps given |context| return `false`, throw a "{{TypeError}}" and abort these steps.

```

2023-01-24 10:43 UTC, anssiko approved these changes

2023-01-24 10:49 UTC, anssiko commented
Thanks @zolkis!

I'll merge this minor change to allow the WG to focus on additional work ahead.

2023-01-24 10:49 UTC, merged