Add the prelu() algorithm
webmachinelearning/webnn pull request #422
Opened 2023-06-26 19:05 UTC by zolkis

Add the prelu() algorithm.

2023-06-27 08:27 UTC, zolkis commented
Depends on #408.

2023-06-29 08:09 UTC, anssiko requested changes

2023-06-29 08:09 UTC, anssiko commented on index.bs
> +    1. Let |descriptor|.{{MLOperandDescriptor/dimensions}} be the result of running the [=MLGraphBuilder/broadcast-shapes=] steps given |input|.{{MLOperand/[[descriptor]]}}.{{MLOperandDescriptor/dime
The CI build fails with:

 `LINE ~3171: No 'dfn' refs found for 'broadcast-shapes'.`

2023-06-29 08:36 UTC, dontcallmedom commented on index.bs
> +    1. Let |descriptor|.{{MLOperandDescriptor/dimensions}} be the result of running the [=MLGraphBuilder/broadcast-shapes=] steps given |input|.{{MLOperand/[[descriptor]]}}.{{MLOperandDescriptor/dime
```suggestion
    1. Let |descriptor|.{{MLOperandDescriptor/dimensions}} be the result of running the [=MLGraphBuilder/broadcast shapes=] steps given |input|.{{MLOperand/[[descriptor]]}}.{{MLOperandDescriptor/dimensions}} and |slope|.{{MLOperand/[[descriptor]]}}.{{MLOperandDescriptor/dimensions}}.
```

2023-06-29 09:32 UTC, anssiko commented
(Merging this PR to the `zk-conventions-integration` integration branch for staging purposes.)

2023-06-29 09:32 UTC, merged